# Render Blueprint Infrastructure Configuration
services:
  # 1. Backend Java Spring Boot Web Service
  - type: web
    name: spendwise-backend-api
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: spendwise-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: spendwise-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: spendwise-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

  # 2. Frontend React Static Site
  - type: web
    name: spendwise-app
    env: static
    buildCommand: bash render-build.sh
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://spendwise-backend-api-rje3.onrender.com/api/v1

databases:
  # 3. PostgreSQL Database
  - name: spendwise-db
    databaseName: spendwisedb
    user: spendwise_user
    plan: free
